### ISSUE TITLE
Throwing java null pointer exception with the version 315

### ISSUE THREAD

**Issue by varun-xempla** [jenkinsci/amazon-inspector-image-scanner-plugin#70]
### Jenkins and plugins versions report

jenkins 2.452.2, ubuntu 22.04, docker image scanning throwing null pointer exception error which absolutely worked fine with the previous versions but throwing error with [315.v956b_b_57f2588](https://updates.jenkins.io/download/plugins/amazon-inspector-image-scanner/315.v956b_b_57f2588/amazon-inspector-image-scanner.hpi)

### What Operating System are you using (both controller, and any agents involved in the problem)?

jenkins master involved in the problem.

### Reproduction steps

please solve the issue 

### Expected Results

it should complete the scan and show if any vulnerabilities are present

### Actual Results

Throwing errors 
Converting SBOM Results to CSV.
Plugin execution ran into an error and is being aborted!
Exception:java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "com.amazon.inspector.jenkins.amazoninspectorbuildstep.models.sbom.Components.Component.getName()" is null
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "com.amazon.inspector.jenkins.amazoninspectorbuildstep.models.sbom.Components.Component.getName()" is null
	at com.amazon.inspector.jenkins.amazoninspectorbuildstep.utils.HtmlConversionUtils.getLineComponents(HtmlConversionUtils.java:81)
	at com.amazon.inspector.jenkins.amazoninspectorbuildstep.csvconversion.CsvConverter.routeDockerCsvData(CsvConverter.java:193)
	at com.amazon.inspector.jenkins.amazoninspectorbuildstep.csvconversion.CsvConverter.routeVulnerabilities(CsvConverter.java:173)
	at com.amazon.inspector.jenkins.amazoninspectorbuildstep.AmazonInspectorBuilder.perform(AmazonInspectorBuilder.java:251)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by waltwilo** [comment]
Hi, please update to version [332.vc76cdef1349e](https://github.com/jenkinsci/amazon-inspector-image-scanner-plugin/releases/tag/332.vc76cdef1349e) and retry your build.

**Comment by varun-xempla** [comment]
hey i have tried using 332.vc76cdef1349e
<https://github.com/jenkinsci/amazon-inspector-image-scanner-plugin/releases/tag/332.vc76cdef1349e>
but
still getting the same error null point exception.

**Comment by waltwilo** [comment]
Is it a different error? That NPE should be handled [here](https://github.com/jenkinsci/amazon-inspector-image-scanner-plugin/blob/main/src/main/java/com/amazon/inspector/jenkins/amazoninspectorbuildstep/html/HtmlConversionUtils.java#L81). If not, please send me your declarative script/UI screenshot; I'll need more info to be able to debug this.

**Comment by waltwilo** [comment]
I pushed another change that should hopefully fix your issue. If the next release doesn't fix your issue. Please provide some more information on your jenkins job so I can try to reproduce the issue.
